// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PI_1.Data.Contexts;

namespace PI_1.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211007114459_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PI_1.Data.Models.CarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CarEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b0e945f-3d24-441d-9174-dd924f93b90a"),
                            Name = "Tesla 1",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = new Guid("3a884ef5-1643-4c40-8f80-e92e0dee96f6"),
                            Name = "Tesla 2",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = new Guid("39a9c96a-fc78-433c-a337-e5e98e114ebc"),
                            Name = "Tesla X",
                            Price = 5000.0
                        });
                });

            modelBuilder.Entity("PI_1.Data.Models.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("OrderEntities");
                });

            modelBuilder.Entity("PI_1.Data.Models.OrderEntity", b =>
                {
                    b.HasOne("PI_1.Data.Models.CarEntity", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("PI_1.Data.Models.CarEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
